service: herenow2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
